influxdb:
  url: http://localhost:8086
  org: Inosat
  token: KKIIV60BcG5u8BYRcPMc3EaZLcvKj73FWg0i3DXkmWUQ5enQtotEVK0VNbiNgTCGQL1bz5z-mOLXoaV_Puv5XQ==
  bucket: inosatiot_resources_sim

electricity:
  - name: counter1
    ep_imp_increment: 2
    ep_exp_increment: 2
    eq_imp_increment: 2
    eq_exp_increment: 2
  - name: counter2
    ep_imp_increment: 1
    ep_exp_increment: 1
    eq_imp_increment: 1
    eq_exp_increment: 1
  - name: counter3
    ep_imp_increment: 3
    ep_exp_increment: 3
    eq_imp_increment: 3
    eq_exp_increment: 3

water:
  - water1
  - water2