# после изменения насроек, в консоли:
# sudo systemctl restart inosatiot_resources_sim.service

influxdb:
  url: http://localhost:8086
  org: __org__
  token: __token__
  bucket: __bucket__

electricity:
  - label: counter1
    p:
      base: 1000
      var: 500
      delay: 300
    q:
      base: 100
      var: 200
      delay: 120
  - label: counter2
    p:
      base: 1500
      var: 1000
      delay: 500
    q:
      base: 100
      var: 200
      delay: 120
  - label: counter3
    p:
      base: 200
      var: 30
      delay: 120
    q:
      base: 100
      var: 200
      delay: 120

water:
  - water1
  - water2