# после изменения насроек, в консоли:
# sudo systemctl restart inosatiot_resources_sim.service

influxdb:
  url: http://localhost:8086
  org: __org__
  token: __token__
  bucket: __bucket__

electricity:
  - label: counter1
    i: [1000, 300, 300]
    v: [230, 10, 20]
    pf: [0.6, 0.2, 40]
    f: [50, 0.2, 3000]
    q_ind: 1
  - label: counter2
    i: [1000, 300, 300]
    v: [230, 10, 20]
    pf: [0.6, 0.2, 40]
    f: [50, 0.2, 3000]
    q_ind: 1
  - label: counter3
    i: [1000, 300, 300]
    v: [230, 10, 20]
    pf: [0.6, 0.2, 40]
    f: [50, 0.2, 3000]
    q_ind: 0